# Generated by Django 3.2.9 on 2021-11-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
